kind: pipeline
name: default

steps:
- name: build and publish docker 
  image: plugins/docker
  settings:
    repo: alexanderwink/build-serverless-go-node
    tags: latest
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD 
